### ISSUE TITLE
API differences with Pako

### ISSUE THREAD

**Issue by ssb22** [photopea/UZIP.js#1]
It's not quite correct to say in the Readme "The API is the same as the API of pako.js" because currently UZip's inflate accepts only a `Uint8Array` whereas Pako can also accept a string. So with Pako I can say `data=pako.inflate("x\xda\xcb\xc8\x04\0\x01;\0\xd2")` but with UZIP.js it has to be `data=UZip.inflate(new Uint8Array([120, 218, 203, 200, 4, 0, 1, 59, 0, 210]))`. Either the readme needs clarifying, or UZip needs to accept a string also.

**Comment by photopea** [comment]
Hi, I always used pako.js with Uint8Array, I didn't even know that it allows to provide data as Strings.

Deflate algorithm works with bytes, so internally, pako still has to convert a String to bytes, which slows down the whole process. Where do your strings come from? Can't you get them as typed arrays instead?

**Comment by ssb22** [comment]
Pako `lib/inflate.js` simply calls `binstring2buf` in its `lib/utils/strings.js` which has a rather simple loop:

    var buf = new utils.Buf8(str.length);
    for (var i = 0, len = buf.length; i < len; i++) {
      buf[i] = str.charCodeAt(i);
    }

Before I looked at the source, I thought it must have done something more "clever" than that, but apparently not!  (`common.js` says `Buf8` is an alias for `Uint8Array`)

**Comment by photopea** [comment]
Yes, you just have to write each character code as a byte

    function s2b(s){  var l=s.length, b=new Uint8Array(l); 
        for(var i=0; i<l; i++) b[i]=s.charCodeAt(i);  return b;  }

If you have a fancy string like "Příliš žlutý" (char codes >255) and want to make a UTF8 text file, you can use UZIP.bin.writeUTF8() . But in general, UZIP is for compression, not for text encodings.

**Comment by ssb22** [comment]
In answer to the question about where my strings come from.  I have a Python script that generates "annotators" which are basically implemented as large state machines.  When porting the output to Javascript, I found the most manageable way to do it was to put the state machine into a simple bytecode in a data string, and write code to 'run' this bytecode.  This means my Javascript comes with a long embedded string (several megabytes' worth) for the bytecode I run.  My downstream developers then put this into phone apps (iOS, Android, Windows) using some Javascript framework which I'm not entirely familiar with, so I'm playing safe by making my part 100% Javascript with no library dependencies (I can't even assume `window` will be there, so no `window.btoa` etc).  However I would like to reduce the size of their apps by reducing the size of my big string.  Compressing it seems the obvious way to go.  But as the input to the decompressor must be something I can represent in my self-contained Javascript source file, it basically either has to be a string, a list of integers (which will be 20% longer than a string), or some other representation for which I need to write a converter and hope it doesn't slow things down too much.

**Comment by photopea** [comment]
I would save binary files in JS code as Base64 strings.  If you can use Uint8Array, you must be able to use btoa, too. E.g. I store PNG images in a JS file for faster loading: https://www.photopea.com/code/PIMG.js

**Comment by ssb22** [comment]
`btoa` is in `window`, and `window` does not exist in `node` and I have no idea if it exists in the various JS frameworks for mobile apps that my generated code is expected to work under.  I could do a "use `btoa`" *option* but I can't assume it'll always be available wherever `Uint8Array` is.

**Comment by photopea** [comment]
You can write Base64 encoder and decoder in 8 lines of JS.  I would like to encourage people to use Typed Arrays, so I would like you to convert strings to typed arrays outside UZIP.js (e.g. using the function s2b above).

**Comment by jimmywarting** [comment]
fyi, to convert string to utf8 buffer
```js
var uint8 = new TextEncoder().encode(str)
```

**Comment by ssb22** [comment]
Thanks but TextEncoder is not universally available (it has minimum browser requirements and is not available on Node).

Uint8Array is available on Node, and on Chrome 7, Firefox 4, IE 10, Opera 11.6, Safari 5.1 and iOS Safari 4.2.

In my Annotator Generator I tried using Uzip with wrapper code and hand-rolled fallbacks for atob and base64 decoding when it detects these are unavailable, but overall it added too much load time to the generated script (especially when one of my downstream developers tried to re-load on every single page display instead of keeping it loaded throughout the lifetime of his app), so I ended up turning off my Uzip option and instead worked on making my string smaller in other ways, such as by using a 6-bit coding for state-table addresses (which puts all address bytes into the printable range, hence reducing the length and load time of my long strings by getting rid of more escape sequences, as escape sequences take up more bytes in the source and also take longer to parse than unescaped strings), and by providing an option to assume it's OK to write UTF-8 characters in annotation strings directly rather than having to encode them (obviously this can't be used if you plan to inject the generated script into an HTML page of unknown character encoding, but there are circumstances in which UTF-8 in source can work and it does save more escaping).

**Comment by photopea** [comment]
@ssb22 You can specify the compression quality for UZIP.deflate(). Level 1 can be 20x faster, than Level 9, but Level 9 would generate 15% smaller result.

**Comment by jimmywarting** [comment]
> TextEncoder is not available on Node

@ssb22  Actually it is [available](https://nodejs.org/api/util.html#util_class_util_textencoder) in node
introduced in v8.3
added as global in v11

**Comment by ssb22** [comment]
Not available when I type "node" on my machine.  May be available via some npm add-on, but I'm using node as installed by the distro as a guide to what is likely to be available in the various phone development kits versus what is a browser-only thing.

Compression level 1 is an interesting idea.  In my case, compression level 1 plus base64 gives an overall size saving of 37% compared with my "6-bit with some UTF-8" approach; that's surprisingly close to the size saving of level 9 which is 43%.  But preliminary tests on my dev box suggest the extra time to load and decode the 10% bigger base64 string outweighs any speedup of UZIP (I get about 10% more overall time when Node.js Buffer is decoding the base64 in both cases, or about 13% more overall time when my fallback code is decoding the base64 in both cases).  And if Buffer is not available and it's my fallback code decoding the Base64, then neither version can beat my "roll-your-own 6-bit" approach on overall load time.

So it seems (in my case) the UZIP-based approach can beat my alternative on load time if and only if Node.js Buffer is available to decode its input Base64 more quickly than my do-it-yourself base64 decoder.  If Node.js Buffer is available then compression level 9 wins, but if the base64 is being decoded by my fallback code then uncompressed wins.  Maybe I'm just not very good at writing a fast base64 decoder.

**Comment by photopea** [comment]
@ssb22 I don't fully understand your use case, but maybe you could use ZIP compression without using base64. Decoding base64 is quite slow, especially when you work with Strings. I wrote my base64 encoder and decoder, which works with ArrayBuffers, and it was quite fast.

**Comment by ssb22** [comment]
zip compression without base64 sounds good in theory, but to include the compressed data in the source, I either have to write a string with lots of \xNN escape codes (which takes 4 bytes per byte whenever the byte isn't printable, and I just tried it and found it generates source 22% larger than my uncompressed 6-bit approach), or I have to write an integer array (also large), or I have to invent my own string code (which I'm very unlikely to make work any faster than base64).  My fallback base64 decoder uses String.charAt to get the base64 out of the string and otherwise uses Uint8Array so it's not obvious how to make it faster.

So, it seems, putting compressed data into JS source makes sense only if window.atob or NodeJS Buffer is available to decode a base64 string at a decent speed.  Otherwise you either take a speed hit or you add size overhead that cancels out the compression.

**Comment by photopea** [comment]
Maybe you could start with telling us what exactly are you trying to achieve :D

If you want to have binary data in a JS file, just use Base64 without any ZIP. JS files are transferred as ZIPped between a browser and a web server, so you don't really save any space.

**Comment by ssb22** [comment]
I'm not dealing with browsers and HTTP.  My downstream developers are putting my code into phone apps using some Javascript framework which I'm not entirely familiar with, and I would like to reduce the size of their apps on end-users' phones, without too much impact on the load time.
