### ISSUE TITLE
Usage in UPNG and UTIF

### ISSUE THREAD

**Issue by 101arrowz** [photopea/UZIP.js#13]
This package claims to be faster than `pako`, so why isn't it used in UPNG or UTIF?

**Comment by photopea** [comment]
Hi, only the decompression is always faster and UPNG uses it (minified e.g. as UPNG.decode._inflate).

The compression is not always better than pako.js and I did not have enough time to do an advanced testing, that is why I stick with pako.js for compression (as it is a port of ZLIB used by billions of people).
