### ISSUE TITLE
Different results of the deflation when using UZIP.js and another Zlib decoder

### ISSUE THREAD

**Issue by yegor-pelykh** [photopea/UZIP.js#17]
I have a Flutter framework application that compresses data using a different Zlib decoder implementation (using [archive package](https://pub.dev/packages/archive)).
And also I have a JS application that uses UZIP.js.
Both of these programs use deflation to create PNG images.

But there is a difference in the output after deflation when using these two different methods.

Let's look at examples of input and output data (all data is placed in files and represents the entire contents of the file read as an array of bytes).

Input data is the same:
[input.txt](https://github.com/photopea/UZIP.js/files/9792169/input.txt)

Output data after calling deflate method using UZIP.js:
[uzip-output.txt](https://github.com/photopea/UZIP.js/files/9792174/deflated.js.txt)

Output data after calling deflate method using `archive` package for Flutter:
[archive-output.txt](https://github.com/photopea/UZIP.js/files/9792177/deflated.dart.txt)

As you can see, the output data differs in both content and length (output data of UZIP.js is larger by 9 bytes).

At the same time, if you create a PNG file using each of these methods, both files will be correct and displayed as an image, which indicates that both methods are valid.

But still, can you please clarify why the output is different?
Which of the output datasets is more correct?
And is it possible to somehow achieve the sameness of the output data by changing something in the use of the UZIP.js?

**Comment by photopea** [comment]
There are millions of ways to compress the data with a DEFLATE method. The same piece of 4128 Bytes can be compressed into hundreds of different files, with a different size, all valid (can be decompressed into the original data). You can even get a file bigger than 4128 Bytes after the compression (e.g. try to compress random bytes). 

Usually, the more time the compression takes, the smaller file you get at the output. So this is just how compression works. Their algorithm is different than ours. You can tell UZIP.js a level of compression to get smaller files (but it will take longer).

**Comment by yegor-pelykh** [comment]
Thank you for the clarification!
It's just that my biggest fears are related to whether these two implementations will normally decompress this data in the opposite direction, regardless of which library was compressed by?
For example, can I expect data compressed by one method to always decompress normally with UZIP.js, taking into account that they have different deflate algorithm?

**Comment by yegor-pelykh** [comment]
@photopea 
Thank you for the clarification!
It's just that my biggest fears are related to whether these two implementations will normally decompress this data in the opposite direction, regardless of which library was compressed by?
For example, can I expect data compressed by one method to always decompress normally with UZIP.js, taking into account that they have different deflate algorithm?

**Comment by photopea** [comment]
There is just one way to decompress a DEFLATE data. If one program decompressed the same data differently than another program, there must be an error in one of them.

When you invent a compression method (representing the original data O with a shorter data S), you only describe the decompression mechanism (how to turn S into O). Then, people compe up with ways how to compress with that method (how to find the S as short as possible, for some data O). It can take decades to invent the best compression methods for an algorithm. DEFLATE compressors keep improving even now, when DEFLATE is 30 years old.


The best compression algorithm for DEFLATE is to try decompress all possible 1-Byte files and check, if they decompress into your original data. If not, try all 2-Byte files, then 3-Byte files, and so on. You will find the shortest file, which is decompressed into your original data, so it is the optimal compressor (but of corse, it would run for weeks or months even for short files).

**Comment by DrSnuggles** [comment]
Hi,
i use UZIP since years in several projects, mostly decompression, without any problem.
None of the provided ZIP files were created by UZIP instead they come from different OS like Win,Linux,Mac,whatever.

UZIP is simple and small (lib size), thanks!!
I also tried and used other libs before i found UZIP but never went back. There is also a ESM version of UZIP: https://github.com/TomasHubelbauer/esm-uzip-js

Example of ZIP compression evolution is Zopfli:
https://en.wikipedia.org/wiki/Zopfli

**Comment by yegor-pelykh** [comment]
Thanks a lot for the clarification! This is a really cool project! I got acquainted with him just recently, having tried "pako" before that. But I have not yet seen a better project for compression! Thank you for this package! 👍

**Comment by yegor-pelykh** [comment]
@DrSnuggles 
I use just original UZIP.js and additionally installed [@types/uzip](https://www.npmjs.com/package/@types/uzip).
This method seemed to me closer to the original than esm-uzip-js project.
