### ISSUE TITLE
Using UZIP.js in UPNG.js

### ISSUE THREAD

**Issue by mn4367** [photopea/UZIP.js#5]
I'm trying to use UZIP.js as a replacement for pako in UPNG.js. I changed this line in UPNG.js

```
if (typeof require == "function") {pako = require("pako");}  else {pako = window.pako;}
```

to this:

```
if (typeof require == "function") {pako = require("./UZIP");}  else {pako = window.pako;}
```

and added
```
if(typeof module !== 'undefined' && typeof module.exports !== 'undefined') module.exports = UZIP;
```

to UZIP.js. This seems to be sufficient to make UZIP.js work as a module in Node.js  If I now execute this code

```
var fs = require("fs");
var input = fs.readFileSync("sample.png");
var PNG = UPNG.decode(input);
var rgba = UPNG.toRGBA8(PNG)[0];
var encoded = UPNG.encode([rgba], 1024, 1024, 0, [], true);
fs.writeFileSync("out.png", Buffer.from(encoded));
```

the code runs fine and `out.png` is created but contains mostly garbage. I also noted, that `UPNG.decode` takes a lot more time to execute. Any hints?

![Bildschirmfoto 2019-07-04 um 10 04 26](https://user-images.githubusercontent.com/6379696/60649975-7259dc80-9e43-11e9-8dcc-5218e61595a3.png)

![Bildschirmfoto 2019-07-04 um 10 05 03](https://user-images.githubusercontent.com/6379696/60649994-80a7f880-9e43-11e9-92ab-3c35af7dc300.png)

**Comment by photopea** [comment]
Hi, it is hard for me to help you, as I never used "require()" or modules. I guess you are using node.js, which I also never used.

I tried to load UPNG.js and UZIP.js inside a HTML file, and replaced two occurences of `pako["deflate"](data);` with `UZIP["deflate"](data);` in UPNG.js  . It works well and PNG files are a bit smaller.

**Comment by photopea** [comment]
I also updated UZIP.js , maybe try the new one.

**Comment by mn4367** [comment]
Thanks for investigating this! I tried the new code and it works if I only replace the two deflate calls with UZIP. If I also replace the inflate call the result I'm getting now looks a bit better (more "correct" pixels at the top of the image):

![Bildschirmfoto 2019-07-05 um 13 31 39](https://user-images.githubusercontent.com/6379696/60719977-8a0b9080-9f29-11e9-8b7c-9ed6956f105a.png)

I know that you're not using Node.js so the code does the following: it reads the complete binary content of the file into a Buffer and passes this Buffer into UPNG.decode. It's essentially the same code I'm using normally but in this case with UZIP instead of pako. The same code using pako gives the correct result.

**Comment by photopea** [comment]
Hi, I updated the UPNG.js too. The new UPNG.js has the Inflate part copy-pasted from UZIP, as it runs faster than Pako. If we copy-paste UZIP compression into UPNG, UPNG would be completely independent on any external libraries.

**Comment by mn4367** [comment]
Thanks, this seems to work now with replacing pako completely with UZIP. I digged a little deeper and logged the results of calling `pako["inflate"]` and `UZIP["inflate"](data)` in UPNG.js. The strange thing is that *depending on the input data* the output of both calls is different. Some files worked, some didn't. I've uploaded some sample files [here](https://www.dropbox.com/s/xjrygioc6e6rbpf/UZIPErrors.zip?dl=0) in case you want to test this..

>  If we copy-paste UZIP compression into UPNG, UPNG would be completely independent on any external libraries.

That was my goal and with the few modifications from above I'm now using UPNG.js without any Node.js module dependencies. Very nice, thank you!

**Comment by photopea** [comment]
What do you mean? There is no `pako["inflate"]` in UPNG.js now. I opened all your PNGs in Photopea.com (which uses the latest UPNG and UZIP) and they worked well.

**Comment by mn4367** [comment]
I mean `pako["inflate"]` before you updated it.

**Comment by photopea** [comment]
It is hard to say what was the problem. I focus only on the latest versions of my code. If you find any problems in the latest code (e.g. pako.inflate returns different data than UZIP.inflate for the same input), let me know.

**Comment by mn4367** [comment]
I'll keep an eye on it, but as I said, with the new version of UPNG.js I encountered no problems so far, for whatever reasons. My only suggestion would be to replace also the deflate functions, I'd see no reasons against it. Thanks very much again!

**Comment by photopea** [comment]
The problem is, that sometimes, UZIP.deflate produces bigger output (worse compression) than pako.deflate . Precisely, UZIP.deflate seems to be better for pictures, while pako.deflate is better for text.

I would have to make several tests, to make sure UZIP.deflate is always better (while running for a similar time).

**Comment by mn4367** [comment]
OK, I see.

If this only in the range of some small percentage I'd consider irrelevant but that's of course your decision. At least for my use case it wouldn't be very important.
