### ISSUE TITLE
Benchmark?

### ISSUE THREAD

**Issue by jimmywarting** [photopea/UZIP.js#8]
Do you have any benchmark?
comparing pako vs uzip...

**Comment by jimmywarting** [comment]
the pastefile in https://github.com/nodeca/pako/issues/136 is gone, what that now is...

**Comment by photopea** [comment]
So unzipping is always faster in UZIP.js . Text comrpession is faster in pako, but compression of other data (which is hard to compress) is faster in UZIP (more or less ...).

I made some tests with a bitmap file in the past. It is not a proper test, as it tests only one specific file.
![40511189-412ac07c-5f9f-11e8-9e44-ebf324840c10](https://user-images.githubusercontent.com/15955558/66633510-4355c280-ec0b-11e9-983d-27704cc3232c.png)
